USE [master]
GO

/****** Object:  Database [CustomProperties]    Script Date: 05/05/2015 17:49:21 ******/
CREATE DATABASE [CustomProperties]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CustomProperties', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\CustomProperties.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CustomProperties_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\CustomProperties_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CustomProperties] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CustomProperties].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CustomProperties] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CustomProperties] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CustomProperties] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CustomProperties] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CustomProperties] SET ARITHABORT OFF 
GO

ALTER DATABASE [CustomProperties] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CustomProperties] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CustomProperties] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CustomProperties] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CustomProperties] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CustomProperties] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CustomProperties] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CustomProperties] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CustomProperties] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CustomProperties] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CustomProperties] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CustomProperties] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CustomProperties] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CustomProperties] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CustomProperties] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CustomProperties] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CustomProperties] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CustomProperties] SET RECOVERY FULL 
GO

ALTER DATABASE [CustomProperties] SET  MULTI_USER 
GO

ALTER DATABASE [CustomProperties] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CustomProperties] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CustomProperties] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CustomProperties] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CustomProperties] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CustomProperties] SET  READ_WRITE 
GO


