//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
[System.Xml.Serialization.XmlRootAttribute("EnrollmentSet", Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0", IsNullable=false)]
public partial class EnrollmentSetType {
    
    private SubscriberEnrollmentType[][] enrollmentsField;
    
    private SubscriberEnrollmentType[] enrollmentsByPlanField;
    
    private SubscriberEnrollmentType[] enrollmentsBySubscriberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Enrollment", typeof(SubscriberEnrollmentType), IsNullable=false)]
    public SubscriberEnrollmentType[][] Enrollments {
        get {
            return this.enrollmentsField;
        }
        set {
            this.enrollmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Enrollment", IsNullable=false)]
    public SubscriberEnrollmentType[] EnrollmentsByPlan {
        get {
            return this.enrollmentsByPlanField;
        }
        set {
            this.enrollmentsByPlanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Enrollment", IsNullable=false)]
    public SubscriberEnrollmentType[] EnrollmentsBySubscriber {
        get {
            return this.enrollmentsBySubscriberField;
        }
        set {
            this.enrollmentsBySubscriberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class SubscriberEnrollmentType {
    
    private string confirmationNumberField;
    
    private System.DateTime dateCompletedField;
    
    private System.Nullable<System.DateTime> dateProcessedField;
    
    private bool dateProcessedFieldSpecified;
    
    private EnrollmentMethodType methodField;
    
    private EnrollmentType typeField;
    
    private SubscriberType subscriberField;
    
    private DependentsType dependentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ConfirmationNumber {
        get {
            return this.confirmationNumberField;
        }
        set {
            this.confirmationNumberField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateCompleted {
        get {
            return this.dateCompletedField;
        }
        set {
            this.dateCompletedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateProcessed {
        get {
            return this.dateProcessedField;
        }
        set {
            this.dateProcessedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateProcessedSpecified {
        get {
            return this.dateProcessedFieldSpecified;
        }
        set {
            this.dateProcessedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public EnrollmentMethodType Method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
    
    /// <remarks/>
    public EnrollmentType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public SubscriberType Subscriber {
        get {
            return this.subscriberField;
        }
        set {
            this.subscriberField = value;
        }
    }
    
    /// <remarks/>
    public DependentsType Dependents {
        get {
            return this.dependentsField;
        }
        set {
            this.dependentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum EnrollmentMethodType {
    
    /// <remarks/>
    AutoEnroll,
    
    /// <remarks/>
    InPerson,
    
    /// <remarks/>
    Online,
    
    /// <remarks/>
    Paper,
    
    /// <remarks/>
    Phone,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum EnrollmentType {
    
    /// <remarks/>
    Cancellation,
    
    /// <remarks/>
    Change,
    
    /// <remarks/>
    InitialEnrollment,
    
    /// <remarks/>
    Waiver,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class SubscriberType : MemberType {
    
    private EmploymentType employmentField;
    
    private string externalIdField;
    
    private string subscriberIdField;
    
    /// <remarks/>
    public EmploymentType Employment {
        get {
            return this.employmentField;
        }
        set {
            this.employmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ExternalId {
        get {
            return this.externalIdField;
        }
        set {
            this.externalIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string SubscriberId {
        get {
            return this.subscriberIdField;
        }
        set {
            this.subscriberIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class EmploymentType {
    
    private EmployerType employerField;
    
    private EmploymentStatusType statusField;
    
    private SalaryType salaryField;
    
    private System.DateTime beginDateField;
    
    private System.DateTime endDateField;
    
    private bool endDateFieldSpecified;
    
    /// <remarks/>
    public EmployerType Employer {
        get {
            return this.employerField;
        }
        set {
            this.employerField = value;
        }
    }
    
    /// <remarks/>
    public EmploymentStatusType Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public SalaryType Salary {
        get {
            return this.salaryField;
        }
        set {
            this.salaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BeginDate {
        get {
            return this.beginDateField;
        }
        set {
            this.beginDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndDateSpecified {
        get {
            return this.endDateFieldSpecified;
        }
        set {
            this.endDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class EmployerType {
    
    private string idField;
    
    private string nameField;
    
    private string externalIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ExternalId {
        get {
            return this.externalIdField;
        }
        set {
            this.externalIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class DependentsType {
    
    private DependentType[] dependentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Dependent")]
    public DependentType[] Dependent {
        get {
            return this.dependentField;
        }
        set {
            this.dependentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class DependentType : MemberType {
    
    private RelationshipType relationshipField;
    
    /// <remarks/>
    public RelationshipType Relationship {
        get {
            return this.relationshipField;
        }
        set {
            this.relationshipField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum RelationshipType {
    
    /// <remarks/>
    Subscriber,
    
    /// <remarks/>
    Spouse,
    
    /// <remarks/>
    Child,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DependentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriberType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class MemberType {
    
    private string memberIdField;
    
    private string firstNameField;
    
    private string middleNameField;
    
    private string lastNameField;
    
    private string suffixField;
    
    private System.DateTime dateOfBirthField;
    
    private System.DateTime dateOfDeathField;
    
    private bool dateOfDeathFieldSpecified;
    
    private GenderType genderField;
    
    private string sSNField;
    
    private string hICNField;
    
    private ContactType personalContactField;
    
    private ContactType workContactField;
    
    private AddressType homeAddressField;
    
    private AddressType mailingAddressField;
    
    private HealthType healthField;
    
    private DisabilityType disabilityField;
    
    private StudentStatusType studentStatusField;
    
    private CoveragesType coveragesField;
    
    private SignatureType signatureField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string MemberId {
        get {
            return this.memberIdField;
        }
        set {
            this.memberIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DateOfBirth {
        get {
            return this.dateOfBirthField;
        }
        set {
            this.dateOfBirthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DateOfDeath {
        get {
            return this.dateOfDeathField;
        }
        set {
            this.dateOfDeathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateOfDeathSpecified {
        get {
            return this.dateOfDeathFieldSpecified;
        }
        set {
            this.dateOfDeathFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public GenderType Gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string SSN {
        get {
            return this.sSNField;
        }
        set {
            this.sSNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string HICN {
        get {
            return this.hICNField;
        }
        set {
            this.hICNField = value;
        }
    }
    
    /// <remarks/>
    public ContactType PersonalContact {
        get {
            return this.personalContactField;
        }
        set {
            this.personalContactField = value;
        }
    }
    
    /// <remarks/>
    public ContactType WorkContact {
        get {
            return this.workContactField;
        }
        set {
            this.workContactField = value;
        }
    }
    
    /// <remarks/>
    public AddressType HomeAddress {
        get {
            return this.homeAddressField;
        }
        set {
            this.homeAddressField = value;
        }
    }
    
    /// <remarks/>
    public AddressType MailingAddress {
        get {
            return this.mailingAddressField;
        }
        set {
            this.mailingAddressField = value;
        }
    }
    
    /// <remarks/>
    public HealthType Health {
        get {
            return this.healthField;
        }
        set {
            this.healthField = value;
        }
    }
    
    /// <remarks/>
    public DisabilityType Disability {
        get {
            return this.disabilityField;
        }
        set {
            this.disabilityField = value;
        }
    }
    
    /// <remarks/>
    public StudentStatusType StudentStatus {
        get {
            return this.studentStatusField;
        }
        set {
            this.studentStatusField = value;
        }
    }
    
    /// <remarks/>
    public CoveragesType Coverages {
        get {
            return this.coveragesField;
        }
        set {
            this.coveragesField = value;
        }
    }
    
    /// <remarks/>
    public SignatureType Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum GenderType {
    
    /// <remarks/>
    Female,
    
    /// <remarks/>
    Male,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class ContactType {
    
    private string emailField;
    
    private string phoneField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class AddressType {
    
    private string line1Field;
    
    private string line2Field;
    
    private string cityField;
    
    private string countyField;
    
    private string countyCodeField;
    
    private string postalCodeField;
    
    private string stateField;
    
    private string stateCodeField;
    
    private string countryField;
    
    private string countryCodeField;
    
    public AddressType() {
        this.countryField = "United States";
        this.countryCodeField = "US";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Line1 {
        get {
            return this.line1Field;
        }
        set {
            this.line1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Line2 {
        get {
            return this.line2Field;
        }
        set {
            this.line2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string County {
        get {
            return this.countyField;
        }
        set {
            this.countyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string CountyCode {
        get {
            return this.countyCodeField;
        }
        set {
            this.countyCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string StateCode {
        get {
            return this.stateCodeField;
        }
        set {
            this.stateCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    [System.ComponentModel.DefaultValueAttribute("United States")]
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    [System.ComponentModel.DefaultValueAttribute("US")]
    public string CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class HealthType {
    
    private decimal heightField;
    
    private bool heightFieldSpecified;
    
    private TobaccoStatusType tobaccoStatusField;
    
    private bool tobaccoStatusFieldSpecified;
    
    private decimal weightField;
    
    private bool weightFieldSpecified;
    
    /// <remarks/>
    public decimal Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HeightSpecified {
        get {
            return this.heightFieldSpecified;
        }
        set {
            this.heightFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public TobaccoStatusType TobaccoStatus {
        get {
            return this.tobaccoStatusField;
        }
        set {
            this.tobaccoStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TobaccoStatusSpecified {
        get {
            return this.tobaccoStatusFieldSpecified;
        }
        set {
            this.tobaccoStatusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WeightSpecified {
        get {
            return this.weightFieldSpecified;
        }
        set {
            this.weightFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum TobaccoStatusType {
    
    /// <remarks/>
    NoUse,
    
    /// <remarks/>
    Use,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class DisabilityType {
    
    private DisabilityStatusType statusField;
    
    private System.DateTime beginDateField;
    
    private System.DateTime endDateField;
    
    private bool endDateFieldSpecified;
    
    /// <remarks/>
    public DisabilityStatusType Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BeginDate {
        get {
            return this.beginDateField;
        }
        set {
            this.beginDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndDateSpecified {
        get {
            return this.endDateFieldSpecified;
        }
        set {
            this.endDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum DisabilityStatusType {
    
    /// <remarks/>
    PermanentlyDisabled,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class StudentStatusType {
    
    private StudentType typeField;
    
    private System.DateTime beginDateField;
    
    private System.DateTime endDateField;
    
    private bool endDateFieldSpecified;
    
    /// <remarks/>
    public StudentType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BeginDate {
        get {
            return this.beginDateField;
        }
        set {
            this.beginDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndDateSpecified {
        get {
            return this.endDateFieldSpecified;
        }
        set {
            this.endDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum StudentType {
    
    /// <remarks/>
    FullTimeStudent,
    
    /// <remarks/>
    PartTimeStudent,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class CoveragesType {
    
    private CoverageType[] coverageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Coverage")]
    public CoverageType[] Coverage {
        get {
            return this.coverageField;
        }
        set {
            this.coverageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class CoverageType {
    
    private CoverageLevelType coverageLevelField;
    
    private PlanType planField;
    
    private ProviderType primaryCareProviderField;
    
    private PremiumType totalPremiumField;
    
    private string groupNumberField;
    
    private MaintenanceType maintenanceTypeField;
    
    private MaintenanceReasonType maintenanceReasonField;
    
    private System.DateTime maintenanceDateField;
    
    private System.DateTime beginDateField;
    
    private System.DateTime endDateField;
    
    private bool endDateFieldSpecified;
    
    private decimal faceAmountField;
    
    private PremiumType memberPremiumField;
    
    private RelationshipType relationshipToSubscriberField;
    
    private System.Xml.XmlElement anyField;
    
    /// <remarks/>
    public CoverageLevelType CoverageLevel {
        get {
            return this.coverageLevelField;
        }
        set {
            this.coverageLevelField = value;
        }
    }
    
    /// <remarks/>
    public PlanType Plan {
        get {
            return this.planField;
        }
        set {
            this.planField = value;
        }
    }
    
    /// <remarks/>
    public ProviderType PrimaryCareProvider {
        get {
            return this.primaryCareProviderField;
        }
        set {
            this.primaryCareProviderField = value;
        }
    }
    
    /// <remarks/>
    public PremiumType TotalPremium {
        get {
            return this.totalPremiumField;
        }
        set {
            this.totalPremiumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string GroupNumber {
        get {
            return this.groupNumberField;
        }
        set {
            this.groupNumberField = value;
        }
    }
    
    /// <remarks/>
    public MaintenanceType MaintenanceType {
        get {
            return this.maintenanceTypeField;
        }
        set {
            this.maintenanceTypeField = value;
        }
    }
    
    /// <remarks/>
    public MaintenanceReasonType MaintenanceReason {
        get {
            return this.maintenanceReasonField;
        }
        set {
            this.maintenanceReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime MaintenanceDate {
        get {
            return this.maintenanceDateField;
        }
        set {
            this.maintenanceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BeginDate {
        get {
            return this.beginDateField;
        }
        set {
            this.beginDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndDateSpecified {
        get {
            return this.endDateFieldSpecified;
        }
        set {
            this.endDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal FaceAmount {
        get {
            return this.faceAmountField;
        }
        set {
            this.faceAmountField = value;
        }
    }
    
    /// <remarks/>
    public PremiumType MemberPremium {
        get {
            return this.memberPremiumField;
        }
        set {
            this.memberPremiumField = value;
        }
    }
    
    /// <remarks/>
    public RelationshipType RelationshipToSubscriber {
        get {
            return this.relationshipToSubscriberField;
        }
        set {
            this.relationshipToSubscriberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum CoverageLevelType {
    
    /// <remarks/>
    Individual,
    
    /// <remarks/>
    IndividualAndChild,
    
    /// <remarks/>
    IndividualAndChildren,
    
    /// <remarks/>
    MarriedCouple,
    
    /// <remarks/>
    DomesticPartnerCouple,
    
    /// <remarks/>
    Family,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class PlanType {
    
    private CarrierType carrierField;
    
    private string externalIdField;
    
    private ProductType productTypeField;
    
    private string nameField;
    
    /// <remarks/>
    public CarrierType Carrier {
        get {
            return this.carrierField;
        }
        set {
            this.carrierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ExternalId {
        get {
            return this.externalIdField;
        }
        set {
            this.externalIdField = value;
        }
    }
    
    /// <remarks/>
    public ProductType ProductType {
        get {
            return this.productTypeField;
        }
        set {
            this.productTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class CarrierType {
    
    private string externalIdField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ExternalId {
        get {
            return this.externalIdField;
        }
        set {
            this.externalIdField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum ProductType {
    
    /// <remarks/>
    Health,
    
    /// <remarks/>
    Dental,
    
    /// <remarks/>
    Vision,
    
    /// <remarks/>
    CriticalIllness,
    
    /// <remarks/>
    Accident,
    
    /// <remarks/>
    TermLife,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class ProviderType {
    
    private string firstNameField;
    
    private string middleNameField;
    
    private string lastNameField;
    
    private string suffixField;
    
    private AddressType addressField;
    
    private ContactType contactField;
    
    private string externalIdField;
    
    private string organizationNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }
    
    /// <remarks/>
    public AddressType Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public ContactType Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ExternalId {
        get {
            return this.externalIdField;
        }
        set {
            this.externalIdField = value;
        }
    }
    
    /// <remarks/>
    public string OrganizationName {
        get {
            return this.organizationNameField;
        }
        set {
            this.organizationNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class PremiumType {
    
    private decimal amountField;
    
    private PremiumFrequencyType frequencyField;
    
    /// <remarks/>
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public PremiumFrequencyType Frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum PremiumFrequencyType {
    
    /// <remarks/>
    Annually,
    
    /// <remarks/>
    Biweekly,
    
    /// <remarks/>
    Monthly,
    
    /// <remarks/>
    Quarterly,
    
    /// <remarks/>
    Semimonthly,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum MaintenanceType {
    
    /// <remarks/>
    Addition,
    
    /// <remarks/>
    Address,
    
    /// <remarks/>
    Cancellation,
    
    /// <remarks/>
    CancellationDate,
    
    /// <remarks/>
    Contact,
    
    /// <remarks/>
    DateOfBirth,
    
    /// <remarks/>
    DateOfDeath,
    
    /// <remarks/>
    EffectiveDate,
    
    /// <remarks/>
    Gender,
    
    /// <remarks/>
    HICN,
    
    /// <remarks/>
    Name,
    
    /// <remarks/>
    Plan,
    
    /// <remarks/>
    Reinstatement,
    
    /// <remarks/>
    SSN,
    
    /// <remarks/>
    Tobacco,
    
    /// <remarks/>
    Void,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum MaintenanceReasonType {
    
    /// <remarks/>
    Adoption,
    
    /// <remarks/>
    Birth,
    
    /// <remarks/>
    ChangeInContactInformation,
    
    /// <remarks/>
    ChangeOfName,
    
    /// <remarks/>
    ChangeOfResidence,
    
    /// <remarks/>
    COBRAEnrolled,
    
    /// <remarks/>
    COBRATerminated,
    
    /// <remarks/>
    Correction,
    
    /// <remarks/>
    Deceased,
    
    /// <remarks/>
    DeceasedEmployee,
    
    /// <remarks/>
    Divorce,
    
    /// <remarks/>
    EmploymentInvoluntarilyEnded,
    
    /// <remarks/>
    EmploymentVoluntarilyEnded,
    
    /// <remarks/>
    LegalSeparation,
    
    /// <remarks/>
    LossOfDependentEligibility,
    
    /// <remarks/>
    LossOfEligibilityForOtherCoverage,
    
    /// <remarks/>
    LossOfEmployerContributionsTowardOtherCoverage,
    
    /// <remarks/>
    Marriage,
    
    /// <remarks/>
    NoLongerEligibleButEmployed,
    
    /// <remarks/>
    Other,
    
    /// <remarks/>
    OtherCoverage,
    
    /// <remarks/>
    PlacementForAdoption,
    
    /// <remarks/>
    ReEnrollment,
    
    /// <remarks/>
    Rehired,
    
    /// <remarks/>
    ReturnFromLeaveOfAbsence,
    
    /// <remarks/>
    SurvivingSpouse,
    
    /// <remarks/>
    Unknown,
    
    /// <remarks/>
    VoluntaryWithdrawal,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class SignatureType {
    
    private System.DateTime dateField;
    
    private string signedNameField;
    
    private SignerType signerField;
    
    /// <remarks/>
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public string SignedName {
        get {
            return this.signedNameField;
        }
        set {
            this.signedNameField = value;
        }
    }
    
    /// <remarks/>
    public SignerType Signer {
        get {
            return this.signerField;
        }
        set {
            this.signerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum SignerType {
    
    /// <remarks/>
    LegalGuardian,
    
    /// <remarks/>
    Observed,
    
    /// <remarks/>
    Parent,
    
    /// <remarks/>
    Member,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public partial class SalaryType {
    
    private decimal amountField;
    
    private SalaryFrequencyType frequencyField;
    
    /// <remarks/>
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public SalaryFrequencyType Frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum SalaryFrequencyType {
    
    /// <remarks/>
    Biweekly,
    
    /// <remarks/>
    Hourly,
    
    /// <remarks/>
    Monthly,
    
    /// <remarks/>
    Weekly,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.arrayhealth.com/Enrollment/v1.0")]
public enum EmploymentStatusType {
    
    /// <remarks/>
    Active,
    
    /// <remarks/>
    COBRA,
}
